sbt:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: mysql
    port: 3306
    username: root
    password: ntjcy@2014

   # AccessKey ID
    #  LTAI5tDZXgD6SgVydKy18N7u

    #  AccessKey Secret
    #  EwvCmq5kswYbmxBbFbAT9nUC4kGyq7
  redis:
     host: localhost
     port: 6379
     password: 123456
     database: 0



