#file: noinspection SpringBootApplicationYaml,SpringBootApplicationYaml,SpringBootApplicationYaml,SpringBootApplicationYaml,SpringBootApplicationYaml
spring:
  profiles:
    active: test
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${court.datasource.host}:${court.datasource.port}/
    username: ${court.datasource.username}
    password: ${court.datasource.password}

  servlet:
    multipart:
      max-request-size: 50MB
      max-file-size: 50MB

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

server:
  port: 8081

#debug: true
# 设置日志级别，root表示根节点，即整体应用日志级别
logging:
  level:
    root: info     #root级别
    #日志级别从低到高：TRACE < DEBUG < INFO（开发） < WARN（生产系统上线时） < ERROR（生产系统上线时）< FATAL
    com.jcj.mydemo: warn     # package级别
  #Spring Boot默认使用LogBack日志系统，日志默认输出到控制台的
  file:  # 日志输入一个固定的地方，存在文件里
    name: logs/system.log        # 将日志存在logs下的system.log日志中



jwt:
    # 设置jwt签名加密时使用的秘钥
  secret-key: nangtongcourtjj1001001
    # 设置jwt过期时间 8小时
  ttl: 28800000
    # 设置前端传递过来的令牌名称
  token-name: Authorization

