sbt:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: 192.168.5.249
    port: 3307
    username: root
    password: 123456


  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 0


