security:
  permit-all: # 权限访问白名单
    - "/login"
    - "/user/**"
  role-based: # 需要权限名单
    - pattern: "/admin/**"
      role: ADMIN
    - pattern: "/manager/**"
      role: MANAGER
jwt:
    # jwt secretKey
  secret-key: nangtongcourtjj1001001
    # token过期时间 毫秒
  ttl: 28800000
    # 请求头
  head-name: Authorization
    # token base
  head-base: "Bearer "

mybatis:
  type-handlers-package: com.ssy.handler #集合类型转换
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    plugins:
      - com.ssy.mybatis.SnowflakeIdInterceptor #拦截器自动生成雪花id